[2024-04-17T07:27:57.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T07:27:57.873+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:26:00+00:00 [queued]>
[2024-04-17T07:27:57.878+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:26:00+00:00 [queued]>
[2024-04-17T07:27:57.920+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-17T07:27:57.933+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello> on 2024-04-16 00:26:00+00:00
[2024-04-17T07:27:57.941+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T07:27:57.942+0000] {standard_task_runner.py:63} INFO - Started process 5352 to run task
[2024-04-17T07:27:57.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_spotify', 'hello', 'scheduled__2024-04-16T00:26:00+00:00', '--job-id', '2767', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5h74gtfn']
[2024-04-17T07:27:57.944+0000] {standard_task_runner.py:91} INFO - Job 2767: Subtask hello
[2024-04-17T07:27:57.994+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:26:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T07:27:58.104+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_spotify' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:26:00+00:00'
[2024-04-17T07:27:58.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T07:28:01.702+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T07:28:05.000+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T07:28:05.004+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-17T07:28:05.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T07:28:05.014+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_spotify, task_id=hello, execution_date=20240416T002600, start_date=20240417T072757, end_date=20240417T072805
[2024-04-17T07:28:05.049+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T07:28:05.071+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T07:28:05.073+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
