[2024-04-17T07:27:57.807+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T07:27:57.827+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:24:00+00:00 [queued]>
[2024-04-17T07:27:57.834+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:24:00+00:00 [queued]>
[2024-04-17T07:27:57.835+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-17T07:27:57.920+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello> on 2024-04-16 00:24:00+00:00
[2024-04-17T07:27:57.928+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5330) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T07:27:57.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_spotify', 'hello', 'scheduled__2024-04-16T00:24:00+00:00', '--job-id', '2766', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw81d41d7']
[2024-04-17T07:27:57.931+0000] {standard_task_runner.py:63} INFO - Started process 5351 to run task
[2024-04-17T07:27:57.931+0000] {standard_task_runner.py:91} INFO - Job 2766: Subtask hello
[2024-04-17T07:27:57.983+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_spotify.hello scheduled__2024-04-16T00:24:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T07:27:58.100+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_spotify' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:24:00+00:00'
[2024-04-17T07:27:58.102+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T07:28:01.666+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T07:28:04.957+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T07:28:04.960+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-17T07:28:04.962+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T07:28:04.973+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_spotify, task_id=hello, execution_date=20240416T002400, start_date=20240417T072757, end_date=20240417T072804
[2024-04-17T07:28:05.000+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T07:28:05.021+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T07:28:05.023+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
