[2024-04-17T05:22:06.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T05:22:06.259+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:48:00+00:00 [queued]>
[2024-04-17T05:22:06.266+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:48:00+00:00 [queued]>
[2024-04-17T05:22:06.267+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-17T05:22:06.277+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello> on 2024-04-16 10:48:00+00:00
[2024-04-17T05:22:06.284+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T05:22:06.285+0000] {standard_task_runner.py:63} INFO - Started process 220 to run task
[2024-04-17T05:22:06.285+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello', 'scheduled__2024-04-16T10:48:00+00:00', '--job-id', '1612', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwi5iivy0']
[2024-04-17T05:22:06.286+0000] {standard_task_runner.py:91} INFO - Job 1612: Subtask hello
[2024-04-17T05:22:06.323+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:48:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T05:22:06.399+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T10:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T10:48:00+00:00'
[2024-04-17T05:22:06.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T05:22:09.953+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T05:22:13.226+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T05:22:13.228+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-17T05:22:13.229+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T05:22:13.235+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=spotify_final_dag, task_id=hello, execution_date=20240416T104800, start_date=20240417T052206, end_date=20240417T052213
[2024-04-17T05:22:13.280+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T05:22:13.299+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T05:22:13.301+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
